service: discovery-service

app: discovery-service

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get